services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      # Additional port for prometheus to connect on and gather metrics
      - "19565:19565"
    environment:
      # The type of server to use chosen from: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/
      TYPE: "AUTO_CURSEFORGE"
      # The Curse Forge Developer Console API key to use type AUTO_CURSEFORGE. Escape $ symbols with an additional $
      CF_API_KEY: ${FORGE_API_KEY}
      # The Curse Forge URL of the modpack to use. Add the verion URL of the specific version at the end to pin the modpack version
      CF_SLUG: "enigmatica2expert"
      CF_FILENAME_MATCHER: "1.90h"
      # Max number of players
      MAX_PLAYERS: 50
      # Server name
      SERVER_NAME: "Block Party"
      STOP_SERVER_ANNOUNCE_DELAY: 30
      # Message of the day
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      # Java memory heap size
      USE_AIKAR_FLAGS: "false"
      INIT_MEMORY: "16G"
      MEMORY: "16G"
      # Set this to allow Minecraft to access more RAM for world generation
      # if you keep getting stuck at "Preparing spawn area"
      MAX_MEMORY: "16G"
      # The Version Minecraft Server to run
      VERSION: "1.12.2"
      # Accept the End User License Agreement
      EULA: "TRUE"
      # Disables reporting to snooper
      SNOOPER_ENABLED: false
      # Sets the spawn protection zone to a 3x3 chunk area
      SPAWN_PROTECTION: 24
      # Adjusts the level type to be large biomes
      LEVEL_TYPE: LARGE_BIOMES
      # Allows flight
      ALLOW_FLIGHT: true
      ENABLE_WHITELIST: false
      # These are our op/admin users
      OPS: |
        Imazing1
        joshcomplex
      JVM_OPTS: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=32M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      minecraft:
        aliases:
          - minecraft
  prometheus:
    image: bitnami/prometheus
    tty: true
    stdin_open: true
    ports:
      - "9090:9090"
    volumes:
      # The path on your local computer where the prometheus configuration exists mapped to /etc/prometheus/prometheus.yml within the prometheus container
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      minecraft:
        aliases:
          - prometheus
  grafana:
    image: grafana/grafana
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      # The path on your local computer where the grafana data will be written to mapped to /var/lib/grafana inside the grafana container
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      minecraft:
        aliases:
          - grafana

# Docker network configurations
networks:
  # The network to configure
  minecraft:
    # The minecraft network will be created if it does not exist
    name: minecraft
